#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-launchy
Version  : 2.4.3
Release  : 10
URL      : https://rubygems.org/downloads/launchy-2.4.3.gem
Source0  : https://rubygems.org/downloads/launchy-2.4.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : ISC
Requires: rubygem-launchy-bin
BuildRequires : ruby
BuildRequires : rubygem-addressable
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-simplecov

%description
# launchy
* [Homepage](https://github.com/copiousfreetime/launchy)
* [Github Project](https://github.com/copiousfreetime/launchy)
* email jeremy at hinegardner dot org

%package bin
Summary: bin components for the rubygem-launchy package.
Group: Binaries

%description bin
bin components for the rubygem-launchy package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n launchy-2.4.3
gem spec %{SOURCE0} -l --ruby > rubygem-launchy.gemspec

%build
gem build rubygem-launchy.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
launchy-2.4.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/launchy-2.4.3 && rake --trace test TESTOPTS="-v" && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/launchy-2.4.3.gem
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/HISTORY.md
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/Manifest.txt
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/README.md
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/bin/launchy
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/lib/launchy.rb
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/lib/launchy/application.rb
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/lib/launchy/applications/browser.rb
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/lib/launchy/argv.rb
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/lib/launchy/cli.rb
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/lib/launchy/deprecated.rb
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/lib/launchy/descendant_tracker.rb
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/lib/launchy/detect.rb
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/lib/launchy/detect/host_os.rb
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/lib/launchy/detect/host_os_family.rb
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/lib/launchy/detect/nix_desktop_environment.rb
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/lib/launchy/detect/ruby_engine.rb
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/lib/launchy/detect/runner.rb
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/lib/launchy/error.rb
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/lib/launchy/os_family.rb
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/lib/launchy/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/spec/application_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/spec/applications/browser_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/spec/cli_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/spec/detect/host_os_family_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/spec/detect/host_os_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/spec/detect/nix_desktop_environment_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/spec/detect/ruby_engine_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/spec/detect/runner_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/spec/launchy_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/spec/mock_application.rb
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/spec/tattle-host-os.yaml
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/spec/version_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/tasks/default.rake
/usr/lib64/ruby/gems/2.3.0/gems/launchy-2.4.3/tasks/this.rb
/usr/lib64/ruby/gems/2.3.0/specifications/launchy-2.4.3.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/launchy
