#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-launchy
Version  : 2.4.3
Release  : 7
URL      : https://rubygems.org/downloads/launchy-2.4.3.gem
Source0  : https://rubygems.org/downloads/launchy-2.4.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : ISC
Requires: rubygem-launchy-bin
BuildRequires : ruby
BuildRequires : rubygem-addressable
BuildRequires : rubygem-docile
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-simplecov
BuildRequires : rubygem-simplecov-html

%description
# launchy
* [Homepage](https://github.com/copiousfreetime/launchy)
* [Github Project](https://github.com/copiousfreetime/launchy)
* email jeremy at hinegardner dot org

%package bin
Summary: bin components for the rubygem-launchy package.
Group: Binaries

%description bin
bin components for the rubygem-launchy package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n launchy-2.4.3
gem spec %{SOURCE0} -l --ruby > rubygem-launchy.gemspec

%build
gem build rubygem-launchy.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
launchy-2.4.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/launchy-2.4.3 && rake --trace test TESTOPTS="-v" && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/launchy-2.4.3.gem
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Application/Browser/app_list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Application/Browser/browser_cmdline-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Application/Browser/browser_env-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Application/Browser/cdesc-Browser.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Application/Browser/cmd_and_args-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Application/Browser/cygwin_app_list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Application/Browser/darwin_app_list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Application/Browser/handles%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Application/Browser/nix_app_list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Application/Browser/open-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Application/Browser/schemes-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Application/Browser/windows_app_list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Application/cdesc-Application.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Application/find_executable-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Application/find_executable-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Application/handling-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Application/host_os_family-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Application/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Application/ruby_engine-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Application/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Application/runner-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/ApplicationNotFoundError/cdesc-ApplicationNotFoundError.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/ArgumentError/cdesc-ArgumentError.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Argv/%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Argv/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Argv/argv-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Argv/blank%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Argv/cdesc-Argv.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Argv/executable%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Argv/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Argv/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Argv/to_str-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Argv/valid%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Browser/_warn-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Browser/cdesc-Browser.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Browser/find_caller_context-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Browser/report_caller_context-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Browser/run-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Browser/visit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Cli/cdesc-Cli.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Cli/error_output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Cli/good_run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Cli/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Cli/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Cli/parse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Cli/parser-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Cli/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/CommandNotFoundError/cdesc-CommandNotFoundError.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/DescendantTracker/cdesc-DescendantTracker.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/DescendantTracker/children-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/DescendantTracker/find_child-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/DescendantTracker/inherited-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOs/cdesc-HostOs.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOs/default_host_os-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOs/host_os-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOs/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOs/override_host_os-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOs/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOs/to_str-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOsFamily/Cygwin/app_list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOsFamily/Cygwin/cdesc-Cygwin.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOsFamily/Cygwin/matching_regex-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOsFamily/Darwin/app_list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOsFamily/Darwin/cdesc-Darwin.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOsFamily/Darwin/matching_regex-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOsFamily/Nix/app_list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOsFamily/Nix/cdesc-Nix.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOsFamily/Nix/matching_regex-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOsFamily/NotFoundError/cdesc-NotFoundError.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOsFamily/Windows/app_list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOsFamily/Windows/cdesc-Windows.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOsFamily/Windows/matching_regex-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOsFamily/cdesc-HostOsFamily.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOsFamily/cygwin%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOsFamily/cygwin%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOsFamily/darwin%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOsFamily/darwin%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOsFamily/detect-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOsFamily/host_os-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOsFamily/matches%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOsFamily/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOsFamily/nix%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOsFamily/nix%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOsFamily/windows%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/HostOsFamily/windows%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/NixDesktopEnvironment/Gnome/browser-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/NixDesktopEnvironment/Gnome/cdesc-Gnome.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/NixDesktopEnvironment/Gnome/is_current_desktop_environment%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/NixDesktopEnvironment/Kde/browser-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/NixDesktopEnvironment/Kde/cdesc-Kde.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/NixDesktopEnvironment/Kde/is_current_desktop_environment%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/NixDesktopEnvironment/NotFound/browser-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/NixDesktopEnvironment/NotFound/cdesc-NotFound.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/NixDesktopEnvironment/NotFound/is_current_desktop_environment%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/NixDesktopEnvironment/NotFoundError/cdesc-NotFoundError.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/NixDesktopEnvironment/Xdg/browser-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/NixDesktopEnvironment/Xdg/cdesc-Xdg.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/NixDesktopEnvironment/Xdg/is_current_desktop_environment%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/NixDesktopEnvironment/Xfce/browser-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/NixDesktopEnvironment/Xfce/cdesc-Xfce.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/NixDesktopEnvironment/Xfce/is_current_desktop_environment%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/NixDesktopEnvironment/browsers-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/NixDesktopEnvironment/cdesc-NixDesktopEnvironment.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/NixDesktopEnvironment/detect-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/NixDesktopEnvironment/fallback_browsers-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/RubyEngine/Jruby/cdesc-Jruby.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/RubyEngine/Jruby/engine_name-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/RubyEngine/MacRuby/cdesc-MacRuby.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/RubyEngine/MacRuby/engine_name-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/RubyEngine/Mri/cdesc-Mri.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/RubyEngine/Mri/engine_name-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/RubyEngine/Mri/is_current_engine%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/RubyEngine/NotFoundError/cdesc-NotFoundError.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/RubyEngine/Rbx/cdesc-Rbx.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/RubyEngine/Rbx/engine_name-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/RubyEngine/cdesc-RubyEngine.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/RubyEngine/detect-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/RubyEngine/is_current_engine%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/RubyEngine/jruby%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/RubyEngine/macruby%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/RubyEngine/mri%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/RubyEngine/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/RubyEngine/rbx%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/RubyEngine/ruby_engine-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/RubyEngine/ruby_engine_error_message-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/RubyEngine/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/Runner/Forkable/cdesc-Forkable.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/Runner/Forkable/child_pid-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/Runner/Forkable/close_file_descriptors-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/Runner/Forkable/exec_or_raise-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/Runner/Forkable/wet_run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/Runner/Jruby/cdesc-Jruby.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/Runner/Jruby/wet_run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/Runner/NotFoundError/cdesc-NotFoundError.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/Runner/Windows/all_args-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/Runner/Windows/cdesc-Windows.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/Runner/Windows/dry_run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/Runner/Windows/shell_commands-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/Runner/Windows/wet_run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/Runner/cdesc-Runner.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/Runner/commandline_normalize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/Runner/detect-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/Runner/dry_run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/Runner/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/Runner/shell_commands-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Detect/cdesc-Detect.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Error/cdesc-Error.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/OSFamily/cdesc-OSFamily.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Version/cdesc-Version.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Version/to_a-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/Version/to_s-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/app_for_uri-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/app_for_uri_string-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/application%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/application-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/bug_report_message-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/cdesc-Launchy.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/debug%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/debug%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/dry_run%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/dry_run%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/extract_global_options-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/host_os%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/host_os-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/log-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/open-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/reset_global_options-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/ruby_engine%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/ruby_engine-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/string_to_uri-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/Launchy/to_bool-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/page-CONTRIBUTING_md.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/page-HISTORY_md.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/page-Manifest_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/launchy-2.4.3/ri/page-README_md.ri
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/HISTORY.md
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/Manifest.txt
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/README.md
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/bin/launchy
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/lib/launchy.rb
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/lib/launchy/application.rb
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/lib/launchy/applications/browser.rb
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/lib/launchy/argv.rb
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/lib/launchy/cli.rb
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/lib/launchy/deprecated.rb
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/lib/launchy/descendant_tracker.rb
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/lib/launchy/detect.rb
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/lib/launchy/detect/host_os.rb
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/lib/launchy/detect/host_os_family.rb
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/lib/launchy/detect/nix_desktop_environment.rb
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/lib/launchy/detect/ruby_engine.rb
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/lib/launchy/detect/runner.rb
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/lib/launchy/error.rb
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/lib/launchy/os_family.rb
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/lib/launchy/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/spec/application_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/spec/applications/browser_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/spec/cli_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/spec/detect/host_os_family_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/spec/detect/host_os_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/spec/detect/nix_desktop_environment_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/spec/detect/ruby_engine_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/spec/detect/runner_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/spec/launchy_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/spec/mock_application.rb
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/spec/tattle-host-os.yaml
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/spec/version_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/tasks/default.rake
/usr/lib64/ruby/gems/2.2.0/gems/launchy-2.4.3/tasks/this.rb
/usr/lib64/ruby/gems/2.2.0/specifications/launchy-2.4.3.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/launchy
